#!/usr/bin/env bash -e

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

cd $APP_HOME

sbt_build_docker_image() {
    check_dependency_java
    check_dependency_docker

    cd $APP_HOME
    chmod +x sbt

    ./sbt docker:stage

    cp -pR $APP_HOME/scripts/docker/content/* target/docker/stage/app
    cd target/docker/stage

    docker build . -t azureiotpcs/telemetry-agent-java:testing
}

sbt_build_docker_image

set +e
