#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/iot-stream-analytics-java"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

    # Some settings are used to connect to an external dependency, e.g. Azure IoT Hub and IoT Hub Manager API
    # Depending on which settings and which dependencies are needed, edit the list of variables
    echo "Starting Stream Analytics..."
    docker run -it -p $PCS_STREAMANALYTICS_WEBSERVICE_PORT:$PCS_STREAMANALYTICS_WEBSERVICE_PORT \
        -e "PCS_STREAMANALYTICS_WEBSERVICE_PORT=$PCS_STREAMANALYTICS_WEBSERVICE_PORT" \
        -e "PCS_IOTHUBREACT_HUB_NAME=$PCS_IOTHUBREACT_HUB_NAME" \
        -e "PCS_IOTHUBREACT_HUB_ENDPOINT=$PCS_IOTHUBREACT_HUB_ENDPOINT" \
        -e "PCS_IOTHUBREACT_HUB_PARTITIONS=$PCS_IOTHUBREACT_HUB_PARTITIONS" \
        -e "PCS_IOTHUBREACT_ACCESS_POLICY=$PCS_IOTHUBREACT_ACCESS_POLICY" \
        -e "PCS_IOTHUBREACT_ACCESS_KEY=$PCS_IOTHUBREACT_ACCESS_KEY" \
        -e "PCS_IOTHUBREACT_ACCESS_HOSTNAME=$PCS_IOTHUBREACT_ACCESS_HOSTNAME" \
        "$DOCKER_IMAGE"
}

run_container

set +e
